name: Check FastAPI Server with Google Sheets Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-fastapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      env:
        ENV_FILE: server/.env
      - run: |
          source $ENV_FILE

      - name: Run FastAPI server from server folder in the background
        run: |
          cd server && nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Check if FastAPI server is running
        run: |
          curl --fail http://localhost:8000/ || exit 1

      - name: Run tests
        run: |
          pytest tests/
