name: Check FastAPI Server with Google Sheets
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-fastapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
      env:
        ENV_FILE: credentials.env
      run: |
        export $(cat $ENV_FILE | xargs)

      - name: Run FastAPI server from server folder in the background
        run: |
          cd server && nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Check if FastAPI server is running
        run: |
          curl --fail http://localhost:8000/ || exit 1

      - name: Run tests
        run: |
          pytest tests/
